#!/bin/bash
set -euxo pipefail
cd ~/

sudo tee /etc/apt/apt.conf <<EOT
// written by dotfiles bvm/install
Acquire::PDiffs "false";
Acquire::Languages { "en"; };
APT::Install-Recommends 0;
APT::Periodic::AutocleanInterval 60;
EOT

sudo rm -f /etc/motd
sudo touch /etc/motd

sudo apt install -y \
    locales-all \
    locales- \
    os-prober- \
    needrestart \
    policy-rcd-declarative-deny-all \
    systemd-zram-generator \
    qemu-guest-agent \
    avahi-daemon \
    sbuild \
    uidmap \
    mmdebstrap \
    git \
    git-email \
    vim \
    devscripts \
    dput \
    qemu-user-static \
    arch-test \
    architecture-properties \
    ca-certificates \
    zsh \
    tmux \
    diffoscope \
    git-buildpackage \
    quilt \
    rsync \
    build-essential \
    curl \
    neomutt \


sudo mkdir -p /media/share
sudo tee /etc/systemd/system/media-share.mount <<EOT
# written by dotfiles bvm/install
[Unit]

[Mount]
What=share
Where=/media/share
Type=9p
Options=rw,noatime,access=client,trans=virtio,uid=1000,gid=1000

[Install]
WantedBy=multi-user.target
EOT

sudo tee /etc/modules-load.d/40-bvm.conf <<EOT
# written by dotfiles bvm/install
usb_storage
binfmt_misc
9p
9pnet_virtio
qemu_fw_cfg
vfat
netfs
fat
virtio_rng
EOT

sudo tee /etc/systemd/system/bvm-modules-disable.service <<EOT
# written by dotfiles bvm/install
[Unit]
After=network.target

[Service]
Type=forking
ExecStart=/sbin/sysctl kernel.modules_disabled=1
TimeoutSec=0
RemainAfterExit=yes
GuessMainPID=no

[Install]
WantedBy=multi-user.target
EOT

sudo systemctl daemon-reload
sudo systemctl enable --now media-share.mount bvm-modules-disable.service

mkdir -p Debian
mkdir -p Source
test -d Source/dotfiles || (cd Source && git clone https://github.com/zeha/dotfiles)

rsync -r Source/dotfiles/bvm/files/ ~/
cp Source/dotfiles/files/.zshrc ~/
cp Source/dotfiles/files/.tmux.conf ~/
sudo cp ~/.vimrc /root/

chmod 0700 .ssh
test -e .ssh/id_ed25519 || ssh-keygen -t ed25519

chsh -s /bin/zsh

test -d piuparts || git clone https://salsa.debian.org/debian/piuparts

chdist create unstable || true

echo
echo ssh-key:
cat .ssh/id_ed25519.pub

echo
echo reboot and run zeha-sbuild-recreate-chroots
