[colors.bright]
black = "#767676"
blue = "#1a8fff"
cyan = "#14ffff"
green = "#23fd00"
magenta = "#fd28ff"
red = "#f2201f"
white = "#ffffff"
yellow = "#fffd00"

[colors.normal]
black = "#000000"
blue = "#0d73cc"
cyan = "#0dcdcd"
green = "#19cb00"
magenta = "#cb1ed1"
red = "#cc0403"
white = "#dddddd"
yellow = "#cecb00"

[colors.primary]
background = "#fcf6e6"
foreground = "#012d3d"

[cursor.style]
blinking = "On"
shape = "Beam"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = false
size = 13.0

[font.normal]
family = "PragmataPro Mono"

[[keyboard.bindings]]
action = "CreateNewWindow"
key = "N"
mods = "Command"

[window]
dynamic_title = true
